data:
  glorys_path: "d:/Mlpr_project/data/bob_1_4_test_crop/cmems_glorys_preprocessed.nc"
  sst_path: "d:/Mlpr_project/data/bob_1_4_test_crop/cmems_sst_preprocessed.nc"
  sss_path: "d:/Mlpr_project/data/bob_1_4_test_crop/cmems_sss_preprocessed.nc"
  sla_uv_path: "d:/Mlpr_project/data/bob_1_4_test_crop/cmems_sla_ugos_vgos_preprocessed.nc"
  argo_path: ""
  full_map: true
  patch_size: 16
  batch_size: 4
  num_workers: 4
  time_train: ["2025-05-01", "2025-12-31"]
  time_test: ["2026-01-01", "2026-03-24"]
  train_samples: 245
  val_samples: 84

model:
  name: "unet2d_test"
  features: ["SST", "SSS", "SLA", "UGOS", "VGOS"]
  in_channels: 5
  out_channels: 52
  filters: [64, 128, 256, 512]

training:
  epochs: 2
  learning_rate: 0.001
  use_argo_loss: false
  lambda_argo: 1.0
  checkpoint_dir: "checkpoints/test"
  results_dir: "results/test"
  backup_dir: "backups/test"
